(ns sslt.core
  (:require [cheshire.core :refer [parse-string generate-string]]
            [sslt.seaver :as s]))

(defn- get-in-path
  [filename]
  (str "resources/swagger/" filename ".json"))

(defn- get-out-path
  [filename]
  (str "out/swagger/" filename ".json"))

(defn read-file
  [filename]
  (parse-string (slurp (get-in-path filename))))

(defn write-file
  [filename sw]
  (let [out-path (get-out-path filename)]
    (spit out-path (generate-string sw {:pretty false}))
    (str filename " has successfully written")))

(defn process-file
  [filename path-methods]
  (try
    (let [in-sw (read-file filename)
          out-sw (s/seave-methods in-sw path-methods)]
      (write-file filename out-sw))
    (catch clojure.lang.ExceptionInfo e
      {:type (type e)
       :cause (.getMessage e)
       :data (ex-data e)})))

(defn get-methods
  [sw]
  (reduce-kv (fn [acc path methods]
               (assoc acc path (mapv keyword (keys methods))))
             (sorted-map)
             (get sw "paths")))

(comment

  (get-methods (read-file "vkkp/vkkp-controls-api-doc"))
  (prn (get-methods (read-file "vkkp/vkkp-deals-api-doc")))
  (get-methods (read-file "vkkp/vkkp-loan-petitions-api-doc"))
  (get-methods (read-file "vkkp/vkkp-loaners-api-doc"))
  (get-methods (read-file "vkkp/vkkp-payments-api-doc"))
  (get-methods (read-file "vkkp/vkkp-pep-api-doc"))

  (process-file "vkkp/vkkp-controls-api-doc"
                {"/blocking-control/blockings/handle" [:post]
                 "/blocking-control/change/control-result" [:post]
                 "/blocking-control/change/revert-to-new" [:post]
                 "/blocking-control/docs/update" [:put]
                 "/blocking-control/findByLoanPetitionId" [:get]
                 "/blocking-control/ownfunds/update" [:put]
                 "/blocking-control/update-mdm" [:post]
                 "/complex-check-control/findByLoanPetitionId" [:get]
                 "/complex-check-control/retry" [:get]
                 "/complex-check-control/update-mdm" [:post]
                 "/controls" [:post]
                 "/controls-settings" [:post]
                 "/controls-settings/all" [:get]
                 "/controls-settings/by-scenario-id/{scenarioId}" [:get]
                 "/controls-settings/by-scenario-ids" [:get]
                 "/controls-settings/by-scenario/{scenarioId}" [:delete]
                 "/controls-settings/{id}" [:get :put]
                 "/controls/findAllByLoanPetitionId" [:get]
                ;;  "/fix-deal-links" [:post]
                 "/fkr-control/change/control-result" [:post]
                 "/fkr-control/findByLoanPetitionId" [:get]
                 "/fkr-control/kurs/send" [:post]
                ;;  "/forbidden-purpose" [:get :post]
                 "/limit-control/change/control-result" [:put]
                 "/limit-control/excel-report" [:get]
                 "/limit-control/findByLoanPetitionId" [:get]
                 "/postponed-condition-control/change/control-result" [:post]
                 "/postponed-condition-control/findByLoanPetitionId" [:get]
                 "/postponed-condition-control/pc/deal/handle" [:post]
                 "/postponed-condition-control/pc/lp/handle" [:post]
                 "/postponed-condition-control/pc/search" [:post]
                 "/purposeful-use-control/change/control-result" [:post]
                 "/purposeful-use-control/find-acc-nums-with-active-puc" [:get]
                 "/purposeful-use-control/findByLoanPetitionId" [:get]
                 "/purposeful-use-control/payments/approved" [:post]
                 "/purposeful-use-control/payments/auto-attach" [:post]
                 "/purposeful-use-control/payments/detach" [:post]
                 "/purposeful-use-control/payments/findByLoanPetitionIds" [:post]
                 "/purposeful-use-control/payments/manual-attach" [:post]
                 "/purposeful-use-control/payments/manual-control" [:post]
                 "/purposeful-use-control/payments/manual-send-to-pim" [:post]
                 "/purposeful-use-control/payments/prefiltered-search/{loanPetitionId}" [:post]
                 "/purposeful-use-control/payments/process-pim" [:post]
                 "/purposeful-use-control/payments/search/{loanPetitionId}" [:post]
                 "/purposeful-use-control/search-status-attach-payments" [:post]})

  (process-file "vkkp/vkkp-deals-api-doc"
                {"/cft-message/status-abs" [:post]
                 "/cft-message/status-abs/{uuid}" [:get]
                 "/conditions/{dealId}" [:get]
                ;;  "/deal-complexity-file/parse" [:post]
                ;;  "/deal-duplicates/remove" [:post]
                 "/deal-sources/find" [:post]
                 "/dealtkmb/create-or-update" [:post]
                 "/dealtkmb/deal-complexity-config" [:get]
                ;;  "/dealtkmb/deal-complexity-config-mock" [:post]
                 "/dealtkmb/department/{dealId}" [:get]
                 "/dealtkmb/findAllByTechnologyIn" [:post]
                 "/dealtkmb/findByContractNumber" [:get]
                 "/dealtkmb/findByDealId" [:get]
                 "/dealtkmb/findByDealUuids" [:post]
                ;;  "/dealtkmb/findByLoanContractId" [:get]
                 "/dealtkmb/findByLoanPetitionId/{loanPetitionId}" [:get]
                 "/dealtkmb/findByTrancheLoanPetition/{loanPetitionId}" [:get]
                 "/dealtkmb/forbiddenTargets/{dealId}" [:get]
                ;;  "/dealtkmb/migrate-is-complexity" [:get]
                 "/dealtkmb/save" [:post]
                 "/dealtkmb/specialPurposes" [:post]
                 "/dealtkmb/specialPurposes/{dealId}" [:get]
                 "/dealtkmb/updatePurpose" [:put]
                 "/dealtranche/findByTrancheId" [:get]
                 "/dealtranche/findByTrancheIds" [:post]
                 "/dealtranche/manual" [:post]
                 "/department" [:get]
                 "/department-ref" [:get :post]
                 "/department-ref/business-sectors" [:get]
                 "/department-ref/rcops" [:get]
                 "/dossier/search-dictionary" [:get]
                 "/dossier/search/{mdmCode}" [:post]
                ;;  "/drp/properties" [:get]
                ;;  "/drp/re-sending" [:post]
                 "/ecm/download/{ecmUuid}" [:get]
                 "/ecm/findByDealId/{dealId}" [:get]
                 "/ecm/findByLoanPetitionId/{loanPetitionId}" [:get]
                 "/ecm/save" [:post]
                 "/ecm/upload" [:post]
                 "/exception-kukirr" [:get :put :post]
                 "/exception-kukirr/{id}" [:delete]
                 "/find" [:get]
                 "/find-from-dc" [:get]
                 "/info/by-id/{dealId}" [:get]
                 "/info/{loanPetitionId}" [:get]
                 "/issuance-order" [:post]
                 "/issuance-order-report/generate" [:post]
                 "/lending-technology-code" [:get]
                 "/loan-form" [:get]
                ;;  "/loan-petition-state" [:post]
                 "/order-accounting/findByOrderLink/{orderLink}" [:get]
                 "/order-accounting/findByOrderLinkCft/{orderLinkCft}" [:get]
                 "/postponed-condition" [:get :post]
                 "/postponed-condition/cancel-send-to-suz" [:post]
                 "/postponed-condition/guid" [:get]
                 "/postponed-condition/send-to-suz" [:post]
                 "/product" [:get]
                 "/raw-document/number" [:get]
                 "/report/kmb/by-loan-petition-id/{loanPetitionId}" [:get]
                 "/report/kmb/by-tranche-id/{trancheId}" [:get]
                 "/report/kmb/report-by-loan-petition-id/{loanPetitionId}" [:get]
                 "/report/kmb/report-by-tranche-id/{trancheId}" [:get]
                 "/report/kmb/save" [:put]
                 "/report/smb/by-loan-petition-id/{loanPetitionId}" [:get]
                 "/report/smb/by-tranche-id/{trancheId}" [:get]
                 "/report/smb/report-by-loan-petition-id/{loanPetitionId}" [:get]
                 "/report/smb/report-by-tranche-id/{trancheId}" [:get]
                 "/report/smb/save" [:put]
                 "/sub-product" [:get]
                 "/sub-product-status" [:get]
                ;;  "/suz-test" [:get]
                 "/timer" [:get :put :post :delete]
                 "/timer/endDate/{startDate}" [:get]
                 "/timer/load-calendar" [:get]
                 "/timer/type-day/{date}" [:get]
                ;;  "/uip/activate" [:post]
                ;;  "/uip/cancel" [:post]
                ;;  "/uip/notifyActivate" [:post]
                ;;  "/uip/notifyTranche" [:post]
                ;;  "/uip/tranche" [:post]
                 })

  (process-file "vkkp/vkkp-loan-petitions-api-doc"
                {
                ;;  "/auth/epa/tech/token" [:get]
                 "/blocking/export" [:post]
                ;;  "/cft-files" [:get]
                ;;  "/cft-files/update-loan-petitions" [:get]
                 "/channels/opsnext/link" [:get]
                 "/channels/opsnext/loanPetitionId" [:get]
                 "/channels/opsnext/task" [:get]
                 "/channels/status" [:get]
                ;;  "/checking-create-parameters-for-control-by-postponed-condition" [:get]
                 "/deal-sources/setting" [:get]
                ;;  "/drp/properties" [:get]
                ;;  "/drp/re-sending" [:post]
                 "/facade/controls/postponed-condition/excel" [:get]
                 "/frkk/base-url" [:get]
                 "/health/info" [:get]
                 "/internal/basic-info-controls-status/{id}" [:get]
                 "/internal/deals/conditions/{agreementNumber}" [:get]
                ;;  "/internal/deals/find?mdmCode={mdmCode}" [:get]
                ;;  "/internal/deals/findByOrderLink/{orderLink}" [:get]
                ;;  "/internal/findByOrderLinkCft/{orderLinkCft}" [:get]
                 "/internal/handle-system-event" [:post]
                ;;  "/internal/is-loan-petition-tranche/{id}" [:get]
                 "/internal/loan-petition" [:post]
                 "/internal/loan-petition/find-by-deal/{dealId}" [:get]
                 "/internal/loan-petition/find-by-tranche/{trancheId}" [:get]
                 "/internal/loan-petition/fix-deal-links" [:post]
                 "/internal/loan-petition/{id}" [:get :put]
                 "/internal/loan-petition/{loanPetitionId}/event/{eventName}" [:post]
                 "/internal/loan-petitions" [:get]
                ;;  "/internal/payer-has-positive-petitions/{mdmCode}" [:get]
                 "/internal/purpose-loan-agreement" [:get]
                 "/internal/purpose-to-loan-petition-ids" [:get]
                 "/internal/{loanPetitionId}/payPurposeDescription" [:get]
                 "/loan-petition" [:post]
                 "/loan-petition/available-statuses" [:post]
                ;;  "/loan-petition/early-completion" [:get :post :delete]
                ;;  "/loan-petition/migrate-is-complexity" [:post]
                 "/loan-petition/save" [:post]
                 "/loan-petition/update-mdm" [:post]
                 "/loan-petition/{id}" [:get :put]
                 "/loan-petition/{loanPetitionId}/event/{eventName}" [:post]
                 "/reference/{code}" [:get]
                 "/scenario" [:get :post]
                 "/scenario/{id}" [:put :delete]
                 "/security/{actionNames}/{loanPetitionId}/verify" [:get]
                 "/token-for-connect-web-socket" [:post]
                 "/token-for-files-socket" [:post]})

  (process-file "vkkp/vkkp-loaners-api-doc"
                {"/cross-reference/slx" [:get]
                 "/extended-profile/category" [:get]
                 "/extended-profile/category/{mdmId}" [:get]
                 "/fccs/docs2" [:get]
                 "/fccs/own-funds" [:get]
                 "/legal-entity/by-acc/{accountNumber}" [:get]
                 "/legal-entity/find-mdm-codes-by-inn-in" [:post]
                 "/legal-entity/full/{mdm}" [:get]
                 "/legal-entity/list" [:post]
                 "/legal-entity/list-full" [:post]
                 "/legal-entity/search" [:get]
                 "/legal-entity/{mdm}" [:get]
                 "/product-profile/account" [:get]
                 "/product-profile/accounts" [:get]
                 "/product-profile/blockings" [:get]
                 "/product-profile/contract-number" [:get]
                 "/product-profile/credit-line/mdm-and-contract-id" [:get]
                 "/product-profile/is-tranche" [:get]
                 "/product-profile/mdm-and-contract-id" [:get]
                 "/product-profile/mdm-and-contract-id-in" [:post]
                 "/product-profile/short-profile-by-mdm-code" [:get]
                 "/relation" [:get]
                 "/with-permissions/extended-profile/category" [:get]
                 "/with-permissions/extended-profile/category/{mdmId}" [:get]
                 "/with-permissions/legal-entity/by-acc/{accountNumber}" [:get]
                 "/with-permissions/legal-entity/full/{mdm}" [:get]
                 "/with-permissions/legal-entity/list" [:post]
                 "/with-permissions/legal-entity/list-full" [:post]
                 "/with-permissions/legal-entity/search" [:get]
                 "/with-permissions/legal-entity/{mdm}" [:get]
                 "/with-permissions/product-profile/account" [:get]
                 "/with-permissions/product-profile/accounts" [:get]})

  (process-file "vkkp/vkkp-payments-api-doc"
                {"/api/health/info" [:get]
                 "/cft/send" [:post]
                 "/excel-report" [:get :post]
                 "/paymentorder/findByAccountNumber/{accountNumber}" [:get]
                 "/paymentorder/findById/{id}" [:get]
                 "/paymentorder/findByIds" [:post]
                 "/paymentorder/findFirstByMappedCode/{mappedCode}" [:get]
                 "/paymentorder/findPaymentOrderConversion/{paymentOrderId}" [:get]
                 "/paymentorder/findPaymentOrderCurrency" [:get]
                 "/paymentorder/findPaymentOrderRub/{paymentOrderId}" [:get]
                 "/paymentorder/findPaymentOrdersCurrency" [:post]
                 "/paymentorder/findPaymentOrdersRub" [:post]
                 "/paymentorder/findPaymentType/{paymentOrderId}" [:get]
                 "/paymentorder/repeat-auto-attach" [:get]
                 "/paymentorder/search" [:post]
                ;;  "/pim/deletePimLogById/{id}" [:delete]
                 "/pim/findAllPimLogWithLimit/{limitReq}" [:get]
                 "/pim/findPimLogByRequestReqId/{requestReqId}" [:get]
                 "/pim/sendToPIMByIds" [:post]
                ;;  "/unprocessedmessage/findUnprocessedMessageById/{id}" [:get]
                ;;  "/unprocessedmessage/getTotalCount" [:get]
                ;;  "/unprocessedmessage/save" [:post]
                 })

  (process-file "vkkp/vkkp-pep-api-doc"
                {"/audit/event" [:post]
                 "/employee" [:get]
                 "/get-epa-token" [:get]
                 "/search/sort" [:get]
                 "/search/users" [:get]
                 "/security/business-categories" [:get]
                 "/security/check/basic" [:get]
                 "/security/check/{actionNames}" [:post]
                 "/security/conditions/{actionNames}" [:get]
                 "/security/user" [:get]
                 "/security/user/roles" [:get]
                 "/security/user/{userId}" [:get]
                 "/security/user/{userId}/roles" [:get]
                 "/security/users" [:post]
                 "/settings/department" [:post]
                 "/settings/departments" [:get]
                 "/settings/departments/{id}" [:get]
                 "/user-session" [:get]
                 "/user-session/block" [:put]
                 })

  )
